apiVersion: apps/v1
kind: Deployment
metadata:
  name: expenses-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: expenses
  template:
    metadata:
      labels:
        app: expenses
    spec:
      containers:
      - name: expenses
        image: prajwalmg159/expenses-service
        ports:
        - containerPort: 3001
---
apiVersion: v1
kind: Service
metadata:
  name: expenses-service
spec:
  selector:
    app: expenses
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3001
