apiVersion: apps/v1
kind: Deployment
metadata:
  name: reports-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: reports
  template:
    metadata:
      labels:
        app: reports
    spec:
      containers:
      - name: reports
        image: prajwalmg159/reports-service
        ports:
        - containerPort: 3002
---
apiVersion: v1
kind: Service
metadata:
  name: reports-service
spec:
  selector:
    app: reports
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3002
